# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f513896d31d0f17f2218acecc4f60004abe65025cc0e2234b8560e30e350edacfe560f90eef2c0fc2c550dea823883c72e63828b0d181835e5acc52a3a085c04

test:
  secret_key_base: d0f98f3485c49701af2efb37009c7518f1a02a48f1854c7d0f9aeeea46dd342136fdefd0038f43ae51dea89bb31ee5645d6eabf18c7d752e4eb053be2142b8f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
